#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bcrypt
Version  : 2.0.0
Release  : 5
URL      : https://pypi.python.org/packages/source/b/bcrypt/bcrypt-2.0.0.tar.gz
Source0  : https://pypi.python.org/packages/source/b/bcrypt/bcrypt-2.0.0.tar.gz
Summary  : Modern password hashing for your software and your servers
Group    : Development/Tools
License  : Apache-2.0
Requires: bcrypt-python
BuildRequires : cffi
BuildRequires : cffi-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python

%description
This is an implementation of a password hashing method, provided via the
crypt(3) and a reentrant interface.  It is fully compatible with
OpenBSD's bcrypt.c for prefix "$2b$", originally by Niels Provos and
David Mazieres.  (Please refer to the included crypt(3) man page for
information on minor compatibility issues for other bcrypt prefixes.)

%package python
Summary: python components for the bcrypt package.
Group: Default

%description python
python components for the bcrypt package.


%prep
%setup -q -n bcrypt-2.0.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
